Dj_shasha/Dj_shasha/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^shasha/',include('shasha.urls',namespace='shasha')),
]

Dj_shasha/shasha/urls.py
from django.conf.urls import url

from shasha import views

urlpatterns=[
    url(r'^index/$',views.index,name='index'),
    url(r'^register/$',views.register,name='register'),
    url(r'^login/$',views.login,name='login'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^jump/(\d+)$',views.jump,name='jump'),
    url(r'^showcart/$',views.showcart,name='showcart'),
    url(r'^subcart/$',views.subcart,name='subcart'),
    url(r'^addcart/$',views.addcart,name='addcart'),
    url(r'^payy/$',views.payy,name='payy'),
    url(r'^payall/$',views.payall,name='payall'),
    # url(r'^spcart/$',views.spcart,name='spcart'),
    url(r'^cart/$',views.cart,name='cart'),
    url(r'^generateorder/$',views.generateorder,name='generateorder'),
    url(r'^orderlist/$',views.orderlist,name='orderlist'),
    url(r'^orderdetail/(\d+)$',views.orderdetail,name='orderdetail'),

    #测试接口
    url(r'^returnurl/$',views.returnurl,name='returnurl'),#支付成功后客户端的页面显示
    url(r'^appnotifyurl/$',views.app_notify_url,name='app_notify_url'),#支付成功后服务器订单的处理
    url(r'^pay/$',views.pay,name='pay'),
]

Dj_shasha/shasha/models.py
from django.db import models

# Create your models here.
class Img(models.Model):
    name=models.CharField(max_length=50)
    path=models.CharField(max_length=256)

    class Meta:
        db_table='ss_img'


class User(models.Model):
    username=models.CharField(max_length=100)
    password=models.CharField(max_length=100)
    token = models.CharField(max_length=255)

    class Meta:
        db_table='ss_user'

class Goods(models.Model):
    name = models.CharField(max_length=100)
    img_path=models.CharField(max_length=255)
    gid = models.CharField(max_length=20)
    price = models.IntegerField()
    market = models.IntegerField()
    region = models.CharField(max_length=255)
    longname = models.CharField(max_length=255)

    class Meta:
        db_table='ss_goods'


class Cart(models.Model):
    user = models.ForeignKey(User)
    goods = models.ForeignKey(Goods)
    number = models.IntegerField()
    selection = models.IntegerField(default=1)
    selectionall = models.IntegerField(default=1)


    class Meta:
        db_table='ss_cart'


class Order(models.Model):
    user = models.ForeignKey(User)
    createtime = models.DateTimeField(auto_now_add=True)
    updatetime = models.DateTimeField(auto_now=True)
    status = models.IntegerField(default=0)
    order_number = models.CharField(max_length=255)

    class Meta:
        db_table='ss_order'


class OrderGoods(models.Model):
    order = models.ForeignKey(Order)
    goods = models.ForeignKey(Goods)
    number = models.IntegerField()

    class Meta:
        db_table='ss_ordergood'

Dj_shasha/templates/ProductList.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
	</head>
	<body>
	</body>
</html>

Dj_shasha/templates/Shopping Cart.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>购物车-莎莎网</title>
		<link rel="dns-prefetch" href="//cdnec.sasa.com">
		<!--预解析-->
		<link rel='icon' href=http://cdnec.sasa.com/public/app/site/statics/favicon.ico type='image/x-icon' />
		<!--图标-->
		<link rel='shortcut icon' href=http://cdnec.sasa.com/public/app/site/statics/favicon.ico type='image/x-icon' />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<!--文档兼容模式-->

		<!--css-->
{#        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">#}
		<link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/iconfont.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/cart.css' %}" />
        <link rel="stylesheet" href="{% static 'css/shopcart.css' %}"/>
		<!--js-->
		<script type="text/javascript" src="{% static 'js/jquery-1.11.0.js' %}"></script>
		<script src="{% static 'js/jquery.cookie.js' %}" type="text/javascript" charset="utf-8"></script>
{#		<script src="{% static 'js/shopcart.js' %}" type="text/javascript" charset="utf-8"></script>#}
		<script src="{% static 'js/common.js' %}" type="text/javascript" charset="utf-8"></script>
		<script src="{% static 'js/topbar.js' %}" type="text/javascript" charset="utf-8"></script>
        <script src="{% static 'js/spcart.js' %}"></script>
	</head>
	<body class="cart">

		<div class="sidebar">

		</div>
		<div class="topbar">
			<div class="page">
				<div class="login-bar">
					<span id="loginBar" style="display: block;">
						<span>欢迎光临莎莎官网！</span>
					<a href="login.html" style="margin-left:10px;">登录</a> <span class="dividing">或 </span>
					<a href="register.html">免费注册</a>
					</span>
					<span id="memberBar" style="display: none;">
	   				 	<span>您好！<span id="uname"></span></span>
					<span class="point" style="color:#cb9966;"><b>0</b> 积分</span>
					<a href="index.html">退出</a>
					</span>
				</div>
				<div class="member-bar">
					<ul>
						<li class="line">
							<div class="member-link">
								<a href="">
									<i class="iconfont"></i>我的账户<i class="iconfont min"></i>
								</a>
								<dl id="mem_dl_247" style="display: none;">
									<dd>
										<a href="/account/login" rel="nofollow">我的订单</a>
									</dd>
									<dd>
										<a href="/account/login" rel="nofollow">我的积分</a>
									</dd>
									<dd>
										<a href="/account/login" rel="nofollow">我的优惠券</a>
									</dd>
									<dd>
										<a href="/account/login" rel="nofollow">我的收藏</a>
									</dd>
									<dd>
										<a href="/account/login" rel="nofollow">我的评价</a>
									</dd>
								</dl>
							</div>
						</li>
						<li class="line">
							<div class="member-link">
								<a href=""><i class="iconfont"></i>我的收藏</a>
							</div>
						</li>
						<li class="line">
							<div class="member-link">
								<a href=""><i class="iconfont"></i>我的站内信</a>
							</div>
						</li>
						<li class="line">
							<div class="member-link">
								<a href="">积分中心</a>
							</div>
						</li>
						<li class="line">
							<div class="member-link">
								<a href="">Global Site</a>
							</div>
						</li>
						<li class="line">
							<div class="member-link">
								<a href="">关注我们<i class="iconfont min"></i></a>
								<dl class="ajust" id="us_246">
									<dt><a href=""><img src="{% static  'img/topbar/add.png'  %}" alt="加入收藏" height="12" width="16">加入收藏</a><a href=""><img src="{% static  'img/topbar/weibo.png'  %}" alt="新浪微博" height="15" width="17">新浪微博</a><a href=""><img src="{% static  'img/topbar/weixin.png'  %}" alt="莎莎微信" height="14" width="17">莎莎微信</a><a href=""><img src="{% static  'img/topbar/youku.png'  %}" alt="优酷视频" height="13" width="17">优酷视频</a></dt>
									<dd style="display: none;"><img src="{% static  'img/topbar/bigweibo.jpg'  %}" alt="新浪微博" width="100px" height="100px"></dd>
									<dd style="display: none;"><img src="{% static  'img/topbar/bigweixin.jpg'  %}" alt="莎莎微信" width="100px" height="100px"></dd>
									<dd style="display: none;"><img src="{% static  'img/topbar/bigyouku.jpg'  %}" alt="优酷视频" width="100px" height="100px"></dd>
								</dl>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="header-main">
			<div class="page">
				<div class="topcarticon fr">
					<div>
						<img src="{% static  'img/hk.png'  %}">&nbsp; &nbsp;
						<img src="{% static  'img/zp.png'  %}">&nbsp;&nbsp;&nbsp;
						<img src="{% static  'img/fp.png'  %}"></div>
				</div>
				<div class="topcart-step01 topcart-step"></div>
				<div class="sotelogo">
					<a href="index.html">
						<img alt="欢迎光临莎莎网" src="{% static  'img/logo.png'  %}" border="0">
					</a>
				</div>
			</div>
		</div>
		<div id="main" class="ui-cart-body page">
			<!-- 购物车开始 -->
			<!-- 购物车主体 -->
			<div id="J_cartContainer" class="cart-container ui-cart-cont">
				<div class="carttitle bticon">
					您的购物车中的商品</div>
				<form action="" method="post">
					<!-- 购物车内容 -->
					<table id="cart_main" class="cart-main" width="100%">
						<tbody>
							<tr>
								<td>
									<div class="ui-cart-tips">
										香港直送商品订单满<label class="color-pink">¥249</label>包邮
									</div>
								</td>
							</tr>
							<!-- 香港直送 -->
							<tr>
								<td>
									<table class="ui-cart-table J_cart-table"></table>
								</td>
							</tr>

                        {% for cart in carts %}
                            <div style="width: 100%;height: 100px;margin-top: 10px">
                                <a href="{% url 'shasha:jump' cart.goods.id%}"><img src="{{ cart.goods.img_path }}" style="width: 100px;height: 100px"></a>
                                <span style="margin-left: 30px">{{ cart.goods.name }}</span>
                                <span class="num" style="margin-left: 30px">数量：{{ cart.number}}</span>
                                <span class="price-num" style="margin-left: 30px">单价：{{ cart.goods.price }}</span>
                                <span class="jian" style="font-size: 50px;margin-left:30px " data-goodid="{{ cart.goods.id }}">-</span>
                                <span class="jia" style="font-size: 50px;margin-left:30px " data-goodid="{{ cart.goods.id }}">+</span>
                                <span class="pay"  data-goodid="{{ cart.goods.id }}">@</span>
                            </div>
                        {% endfor %}
						<tfoot id="J_cartPriceCont" class="ui-cart-foot">
							<tr>
								<td>
									<table class="ui-cart-table" id="J_orderPrice">
										<tbody>

											<tr>
												<td class="ui-cartfoot-check">
													<div class="fl">
														<a href="index.html" class="ui-cartfoot-link mr20">继续购物</a>
														<a id="J_actionClean" href="{% url 'shasha:orderlist' %}">查看订单</a>
                                                        <span class="payall"  data-isall="{{ cart.selection }}">@</span>
													</div>
													<div class="fr">
														<span class="ui-cartfoot-label">共 <span class="red items-quantity">{{number}}</span> 件商品</span>
														<span class="ui-cartfoot-label">商品应付金额
                <strong class="red f18 promotion-subtotal ui-cart-total">¥{{ price }}</strong>
              </span>

                                                            <a href="{% url 'shasha:generateorder' %}">
                                                            <input type="button" style="margin-right: 10px" class="btn btn-import btn-huge action-settle" value="下单">
                                                            </a>
													</div>
												</td>
											</tr>
											<tr class="ui-carttable-placeholder">
												<td></td>
											</tr>
										</tbody>
									</table>
								</td>
							</tr>
						</tfoot>
					</table>
				</form>
			</div>
			<!-- 加价区 -->

		</div>

{#<script src="/static/js/jiaoben.js"></script>#}

	</body>
{#<script src="{% static 'js/jiaoben.js' %}"></script>#}
</html>

Dj_shasha/templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<link rel="dns-prefetch" href="//cdnec.sasa.com">
		<!--预解析-->
		<link rel='icon' href=http://cdnec.sasa.com/public/app/site/statics/favicon.ico type='image/x-icon' />
		<!--图标-->
		<link rel='shortcut icon' href=http://cdnec.sasa.com/public/app/site/statics/favicon.ico type='image/x-icon' />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<!--文档兼容模式-->
		<title>莎莎网-登录</title>

		<!--css-->
		<link rel="stylesheet" href="{% static 'css/common.css' %}" />
		<link rel="stylesheet" href="{% static 'css/iconfont.css' %}" />
		<link rel="stylesheet" href="{% static 'css/signup.css' %}" />
		<!--js-->
		<script type="text/javascript" src="{% static 'js/jquery-1.11.0.js' %}"></script>
		<script src="{% static 'js/jquery.cookie.js' %}" type="text/javascript" charset="utf-8"></script>
		<script src="{% static 'js/topbar.js' %}" type="text/javascript" charset="utf-8"></script>
		<script src="{% static 'js/login.js' %}" type="text/javascript" charset="utf-8"></script>
	</head>
	<body id="signup">
				<!--顶部-->
		<div class="topbar">
			<div class="page">
				<div class="login-bar">
					<span><span>欢迎光临莎莎官网！</span>
					<a href="login.html" style="margin-left:10px;">登录</a> <span class="dividing">或 </span>
					<a href="register.html">免费注册</a>
					</span>
				</div>
				<div class="member-bar">
					<ul>
						<li class="line">
							<div class="member-link">
								<a href="">
									<i class="iconfont"></i>我的账户<i class="iconfont min"></i>
								</a>
								<dl id="mem_dl_247" style="display: none;">
									<dd>
										<a href="/account/login" rel="nofollow">我的订单</a>
									</dd>
									<dd>
										<a href="/account/login" rel="nofollow">我的积分</a>
									</dd>
									<dd>
										<a href="/account/login" rel="nofollow">我的优惠券</a>
									</dd>
									<dd>
										<a href="/account/login" rel="nofollow">我的收藏</a>
									</dd>
									<dd>
										<a href="/account/login" rel="nofollow">我的评价</a>
									</dd>
								</dl>
							</div>
						</li>
						<li class="line">
							<div class="member-link">
								<a href=""><i class="iconfont"></i>我的收藏</a>
							</div>
						</li>
						<li class="line">
							<div class="member-link">
								<a href=""><i class="iconfont"></i>我的站内信</a>
							</div>
						</li>
						<li class="line">
							<div class="member-link">
								<a href="">积分中心</a>
							</div>
						</li>
						<li class="line">
							<div class="member-link">
								<a href="">Global Site</a>
							</div>
						</li>
						<li class="line">
							<div class="member-link">
								<a href="">关注我们<i class="iconfont min"></i></a>
								<dl class="ajust" id="us_246">
									<dt><a href=""><img src="{% static  'img/topbar/add.png'  %}" alt="加入收藏" height="12" width="16">加入收藏</a><a href=""><img src="{% static  'img/topbar/weibo.png'  %}" alt="新浪微博" height="15" width="17">新浪微博</a><a href=""><img src="{% static  'img/topbar/weixin.png'  %}" alt="莎莎微信" height="14" width="17">莎莎微信</a><a href=""><img src="{% static  'img/topbar/youku.png'  %}" alt="优酷视频" height="13" width="17">优酷视频</a></dt>
									<dd style="display: none;"><img src="{% static  'img/topbar/bigweibo.jpg'  %}" alt="新浪微博" width="100px" height="100px"></dd>
									<dd style="display: none;"><img src="{% static  'img/topbar/bigweixin.jpg'  %}" alt="莎莎微信" width="100px" height="100px"></dd>
									<dd style="display: none;"><img src="{% static  'img/topbar/bigyouku.jpg'  %}" alt="优酷视频" width="100px" height="100px"></dd>
								</dl>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="header-main page">
			<div class="sotelogo">
				<a href="index.html"><img alt="Ecstore-demo" src="{% static  'img/logo.png'  %}" border="0"></a>
			</div>
		</div>
		<div class="login_con page">
			<div class="signin_wrap">
				<div class="signin">
					<div class="sign-title">
						<div class="sign-title-text">
							用户登录<span class="fr">还没有莎莎账号？<a href="{% url 'shasha:register' %}">立即注册</a></span>
						</div>
					</div>
					<div class="signup_box">
						<form action="{% url 'shasha:login' %}" method="post">
                            {% csrf_token %}
							<ul>
								<li class="form-item">
									<label for="" class="form-label">邮箱/手机：</label>
									<span class="form-act"><input class="icon-yhm x-input" type="text" name="username"  placeholder="邮箱/手机"></span><span>{{ err1 }}</span>
								</li>
								<li class="form-item">
									<label for="" class="form-label">密码：</label>
									<span class="form-act"><input class="icon-mm x-input" type="password" name="password" maxlength="16" placeholder="填写密码"></span><span>{{ err }}</span>
								</li>
								<!--<li class="form-item action-verifycode hide">
									<label for="" class="form-label">验证码：</label>
									<span class="form-act">
        <input class="img_input" type="text" name="verifycode" placeholder="填写图片验证码" maxlength="4" autocomplete="off"> <img src="/index-gen_vcode-b2c-4.html" alt="验证码" title="点击更换验证码" class="verify-code auto-change-verify-handle"> <a href="/index-gen_vcode-b2c-4.html" class="verify-code auto-change-verify-handle">看不清?换一张</a>      </span>
								</li>
								<li class="form-item action-need-verify" style="display:none;">
									<label for="" class="form-label">验证码：</label>
									<span class="form-act">
        <input class="x-input verify-input" type="text" name="mobileVcode" id="dom_el_23bf1a3" placeholder="填写验证码"> <a href="/passport-send_vcode_sms.html" class="btn btn-caution action-get-verifycode"><span><span>获取短信验证码</span></span>
									</a>
									</span>
								</li>-->
								<li class="form-item">
									<label for="" class="form-label"></label>
									<span class="form-act"><input type="checkbox" name="site_autologin" id="for_auto_signin" class="x-check action-auto-signin"><label for="" class="form-sub-label">记住我</label><a href="/passport-lost.html" style="color:#ed3f7e;">忘记密码？</a></span>
								</li>
								<li class="form-item-normal">
									<span class="form-act">
                                        <input class="btn btn-major btn-big" type="submit" value="登录">
									</span>
								</li>
							</ul>
						</form>
					</div>
					<div class="other-login">
						<p>第三方账号登录</p>
						<ul>
							<li>
								<a href="/qqlogin-trust_login.html"><img src="{% static  'img/login/qq.jpg'  %}">QQ登录</a>
							</li>
							<li>
								<a href="/wblogin-login.html"><img src="{% static  'img/login/weibo.jpg'  %}">微博登录</a>
							</li>
							<li>
								<a href="/alipaylogin-login.html"><img src="{% static  'img/login/zhifubao.jpg'  %}">支付宝登录</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="theme-footer"><p style="text-align: center;"><font face="Helvetica Neue, Helvetica, Tahoma, Arial, sans-serif"><span style="font-size: 13px; line-height: 20px;"><font color="#999999">© Copyright 2000-2016 Sa Sa dot Com Limited 版权所有。 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 莎莎国际控股有限公司成员</font></span></font></p>
 </div>
    </body>
{#     <script src="{% static 'js/jiaoben.js' %}"></script>#}
</html>

Dj_shasha/templates/orderlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>订单列表</title>
</head>
<body>
<div>
    {% for order in orders %}
        <p>
            <a href="{% url 'shasha:orderdetail' order.order_number %}">
                订单号：{{ order.order_number }}
                {% if order.status == 0 %}
                    未付款
                {% elif order.status == 1 %}
                    待发货
                {% elif order.status == 2 %}
                    待收货
                {% elif order.status == 3 %}
                    待评价
                {% elif order.status == 4 %}
                    已评价
                {% endif %}
            </a>
        </p>
        <br>
    {% endfor %}
</div>
</body>
</html>

Dj_shasha/templates/ordertail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>订单详情</title>
</head>
<body>
<h1>订单详情如下:</h1>
<p>订单号：{{ order.order_number }}</p>
<ul>
    {% for ordergoods in order.ordergoods_set.all %}
        <li>
{#            <img src="{{ ordergoods.goods.path }}">#}
            <span>{{ ordergoods.goods.name }}</span>
            &nbsp;
            <i>{{ ordergoods.number }}</i>
        </li>
    {% endfor %}

</ul>
<button id="alipay" data-orderid="{{ order.id }}">支付</button>
<p>
    <a href="{% url 'shasha:index' %}">返回首页</a>
</p>
<script src="{% static 'js/jquery-1.11.0.js' %}"></script>
<script src="{% static 'js/ordertall.js' %}"></script>
</body>
</html>

Dj_shasha/templates/shop1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>商品详情</title>
</head>
<body>
<div style="width: 300px;float:left;margin-left: 50px">
    <span style="position: relative;left:170px;top: 40px;color: #ee9c23">进口源：</span>
    <img src="{{ good.region }}" style="position: relative;top: 50px;left: 180px">
    <a href="{% url 'shasha:jump' good.id %}"><img src="{{ good.img_path }}"></a>
    <span style="color: #ee9c23">{{ good.name }}-仅售{{ good.price }}&nbsp;&nbsp;&nbsp;&nbsp;-原价：{{ good.market }}</span><br>
    <span style="color: black;"><strong>{{ good.longname }}</strong></span>
</div>
</body>
</html>